# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orders.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0corders.proto\"\xaa\x02\n\x05Order\x12\x0c\n\x04\x63ol1\x18\x01 \x01(\x03\x12\x0c\n\x04\x63ol2\x18\x02 \x01(\t\x12\x0c\n\x04\x63ol3\x18\x03 \x01(\t\x12\x0c\n\x04\x63ol4\x18\x04 \x01(\t\x12\x0c\n\x04\x63ol5\x18\x05 \x01(\t\x12\x0c\n\x04\x63ol6\x18\x06 \x01(\t\x12\x0c\n\x04\x63ol7\x18\x07 \x01(\t\x12\x0c\n\x04\x63ol8\x18\x08 \x01(\t\x12\x0c\n\x04\x63ol9\x18\t \x01(\t\x12\r\n\x05\x63ol10\x18\n \x01(\x02\x12\r\n\x05\x63ol11\x18\x0b \x01(\x02\x12\r\n\x05\x63ol12\x18\x0c \x01(\x02\x12\r\n\x05\x63ol13\x18\r \x01(\x02\x12\r\n\x05\x63ol14\x18\x0e \x01(\x02\x12\r\n\x05\x63ol15\x18\x0f \x01(\x02\x12\r\n\x05\x63ol16\x18\x10 \x01(\x02\x12\r\n\x05\x63ol17\x18\x11 \x01(\x02\x12\r\n\x05\x63ol18\x18\x12 \x01(\x02\x12\r\n\x05\x63ol19\x18\x13 \x01(\x02\x12\r\n\x05\x63ol20\x18\x14 \x01(\x02\"\x0e\n\x0cOrderRequest\"\'\n\rOrderResponse\x12\x16\n\x06orders\x18\x01 \x03(\x0b\x32\x06.Order26\n\x06Orders\x12,\n\tGetOrders\x12\r.OrderRequest\x1a\x0e.OrderResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orders_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ORDER._serialized_start=17
  _ORDER._serialized_end=315
  _ORDERREQUEST._serialized_start=317
  _ORDERREQUEST._serialized_end=331
  _ORDERRESPONSE._serialized_start=333
  _ORDERRESPONSE._serialized_end=372
  _ORDERS._serialized_start=374
  _ORDERS._serialized_end=428
# @@protoc_insertion_point(module_scope)
