from google.protobuf.internal import containers as _containers
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from typing import ClassVar as _ClassVar, Iterable as _Iterable, Mapping as _Mapping, Optional as _Optional, Union as _Union

DESCRIPTOR: _descriptor.FileDescriptor

class Order(_message.Message):
    __slots__ = ["col1", "col10", "col100", "col11", "col12", "col13", "col14", "col15", "col16", "col17", "col18", "col19", "col2", "col20", "col21", "col22", "col23", "col24", "col25", "col26", "col27", "col28", "col29", "col3", "col30", "col31", "col32", "col33", "col34", "col35", "col36", "col37", "col38", "col39", "col4", "col40", "col41", "col42", "col43", "col44", "col45", "col46", "col47", "col48", "col49", "col5", "col50", "col51", "col52", "col53", "col54", "col55", "col56", "col57", "col58", "col59", "col6", "col60", "col61", "col62", "col63", "col64", "col65", "col66", "col67", "col68", "col69", "col7", "col70", "col71", "col72", "col73", "col74", "col75", "col76", "col77", "col78", "col79", "col8", "col80", "col81", "col82", "col83", "col84", "col85", "col86", "col87", "col88", "col89", "col9", "col90", "col91", "col92", "col93", "col94", "col95", "col96", "col97", "col98", "col99"]
    COL100_FIELD_NUMBER: _ClassVar[int]
    COL10_FIELD_NUMBER: _ClassVar[int]
    COL11_FIELD_NUMBER: _ClassVar[int]
    COL12_FIELD_NUMBER: _ClassVar[int]
    COL13_FIELD_NUMBER: _ClassVar[int]
    COL14_FIELD_NUMBER: _ClassVar[int]
    COL15_FIELD_NUMBER: _ClassVar[int]
    COL16_FIELD_NUMBER: _ClassVar[int]
    COL17_FIELD_NUMBER: _ClassVar[int]
    COL18_FIELD_NUMBER: _ClassVar[int]
    COL19_FIELD_NUMBER: _ClassVar[int]
    COL1_FIELD_NUMBER: _ClassVar[int]
    COL20_FIELD_NUMBER: _ClassVar[int]
    COL21_FIELD_NUMBER: _ClassVar[int]
    COL22_FIELD_NUMBER: _ClassVar[int]
    COL23_FIELD_NUMBER: _ClassVar[int]
    COL24_FIELD_NUMBER: _ClassVar[int]
    COL25_FIELD_NUMBER: _ClassVar[int]
    COL26_FIELD_NUMBER: _ClassVar[int]
    COL27_FIELD_NUMBER: _ClassVar[int]
    COL28_FIELD_NUMBER: _ClassVar[int]
    COL29_FIELD_NUMBER: _ClassVar[int]
    COL2_FIELD_NUMBER: _ClassVar[int]
    COL30_FIELD_NUMBER: _ClassVar[int]
    COL31_FIELD_NUMBER: _ClassVar[int]
    COL32_FIELD_NUMBER: _ClassVar[int]
    COL33_FIELD_NUMBER: _ClassVar[int]
    COL34_FIELD_NUMBER: _ClassVar[int]
    COL35_FIELD_NUMBER: _ClassVar[int]
    COL36_FIELD_NUMBER: _ClassVar[int]
    COL37_FIELD_NUMBER: _ClassVar[int]
    COL38_FIELD_NUMBER: _ClassVar[int]
    COL39_FIELD_NUMBER: _ClassVar[int]
    COL3_FIELD_NUMBER: _ClassVar[int]
    COL40_FIELD_NUMBER: _ClassVar[int]
    COL41_FIELD_NUMBER: _ClassVar[int]
    COL42_FIELD_NUMBER: _ClassVar[int]
    COL43_FIELD_NUMBER: _ClassVar[int]
    COL44_FIELD_NUMBER: _ClassVar[int]
    COL45_FIELD_NUMBER: _ClassVar[int]
    COL46_FIELD_NUMBER: _ClassVar[int]
    COL47_FIELD_NUMBER: _ClassVar[int]
    COL48_FIELD_NUMBER: _ClassVar[int]
    COL49_FIELD_NUMBER: _ClassVar[int]
    COL4_FIELD_NUMBER: _ClassVar[int]
    COL50_FIELD_NUMBER: _ClassVar[int]
    COL51_FIELD_NUMBER: _ClassVar[int]
    COL52_FIELD_NUMBER: _ClassVar[int]
    COL53_FIELD_NUMBER: _ClassVar[int]
    COL54_FIELD_NUMBER: _ClassVar[int]
    COL55_FIELD_NUMBER: _ClassVar[int]
    COL56_FIELD_NUMBER: _ClassVar[int]
    COL57_FIELD_NUMBER: _ClassVar[int]
    COL58_FIELD_NUMBER: _ClassVar[int]
    COL59_FIELD_NUMBER: _ClassVar[int]
    COL5_FIELD_NUMBER: _ClassVar[int]
    COL60_FIELD_NUMBER: _ClassVar[int]
    COL61_FIELD_NUMBER: _ClassVar[int]
    COL62_FIELD_NUMBER: _ClassVar[int]
    COL63_FIELD_NUMBER: _ClassVar[int]
    COL64_FIELD_NUMBER: _ClassVar[int]
    COL65_FIELD_NUMBER: _ClassVar[int]
    COL66_FIELD_NUMBER: _ClassVar[int]
    COL67_FIELD_NUMBER: _ClassVar[int]
    COL68_FIELD_NUMBER: _ClassVar[int]
    COL69_FIELD_NUMBER: _ClassVar[int]
    COL6_FIELD_NUMBER: _ClassVar[int]
    COL70_FIELD_NUMBER: _ClassVar[int]
    COL71_FIELD_NUMBER: _ClassVar[int]
    COL72_FIELD_NUMBER: _ClassVar[int]
    COL73_FIELD_NUMBER: _ClassVar[int]
    COL74_FIELD_NUMBER: _ClassVar[int]
    COL75_FIELD_NUMBER: _ClassVar[int]
    COL76_FIELD_NUMBER: _ClassVar[int]
    COL77_FIELD_NUMBER: _ClassVar[int]
    COL78_FIELD_NUMBER: _ClassVar[int]
    COL79_FIELD_NUMBER: _ClassVar[int]
    COL7_FIELD_NUMBER: _ClassVar[int]
    COL80_FIELD_NUMBER: _ClassVar[int]
    COL81_FIELD_NUMBER: _ClassVar[int]
    COL82_FIELD_NUMBER: _ClassVar[int]
    COL83_FIELD_NUMBER: _ClassVar[int]
    COL84_FIELD_NUMBER: _ClassVar[int]
    COL85_FIELD_NUMBER: _ClassVar[int]
    COL86_FIELD_NUMBER: _ClassVar[int]
    COL87_FIELD_NUMBER: _ClassVar[int]
    COL88_FIELD_NUMBER: _ClassVar[int]
    COL89_FIELD_NUMBER: _ClassVar[int]
    COL8_FIELD_NUMBER: _ClassVar[int]
    COL90_FIELD_NUMBER: _ClassVar[int]
    COL91_FIELD_NUMBER: _ClassVar[int]
    COL92_FIELD_NUMBER: _ClassVar[int]
    COL93_FIELD_NUMBER: _ClassVar[int]
    COL94_FIELD_NUMBER: _ClassVar[int]
    COL95_FIELD_NUMBER: _ClassVar[int]
    COL96_FIELD_NUMBER: _ClassVar[int]
    COL97_FIELD_NUMBER: _ClassVar[int]
    COL98_FIELD_NUMBER: _ClassVar[int]
    COL99_FIELD_NUMBER: _ClassVar[int]
    COL9_FIELD_NUMBER: _ClassVar[int]
    col1: int
    col10: str
    col100: float
    col11: float
    col12: float
    col13: float
    col14: float
    col15: float
    col16: float
    col17: float
    col18: float
    col19: float
    col2: str
    col20: float
    col21: float
    col22: float
    col23: float
    col24: float
    col25: float
    col26: float
    col27: float
    col28: float
    col29: float
    col3: str
    col30: float
    col31: float
    col32: float
    col33: float
    col34: float
    col35: float
    col36: float
    col37: float
    col38: float
    col39: float
    col4: str
    col40: float
    col41: float
    col42: float
    col43: float
    col44: float
    col45: float
    col46: float
    col47: float
    col48: float
    col49: float
    col5: str
    col50: float
    col51: float
    col52: float
    col53: float
    col54: float
    col55: float
    col56: float
    col57: float
    col58: float
    col59: float
    col6: str
    col60: float
    col61: float
    col62: float
    col63: float
    col64: float
    col65: float
    col66: float
    col67: float
    col68: float
    col69: float
    col7: str
    col70: float
    col71: float
    col72: float
    col73: float
    col74: float
    col75: float
    col76: float
    col77: float
    col78: float
    col79: float
    col8: str
    col80: float
    col81: float
    col82: float
    col83: float
    col84: float
    col85: float
    col86: float
    col87: float
    col88: float
    col89: float
    col9: str
    col90: float
    col91: float
    col92: float
    col93: float
    col94: float
    col95: float
    col96: float
    col97: float
    col98: float
    col99: float
    def __init__(self, col1: _Optional[int] = ..., col2: _Optional[str] = ..., col3: _Optional[str] = ..., col4: _Optional[str] = ..., col5: _Optional[str] = ..., col6: _Optional[str] = ..., col7: _Optional[str] = ..., col8: _Optional[str] = ..., col9: _Optional[str] = ..., col10: _Optional[str] = ..., col11: _Optional[float] = ..., col12: _Optional[float] = ..., col13: _Optional[float] = ..., col14: _Optional[float] = ..., col15: _Optional[float] = ..., col16: _Optional[float] = ..., col17: _Optional[float] = ..., col18: _Optional[float] = ..., col19: _Optional[float] = ..., col20: _Optional[float] = ..., col21: _Optional[float] = ..., col22: _Optional[float] = ..., col23: _Optional[float] = ..., col24: _Optional[float] = ..., col25: _Optional[float] = ..., col26: _Optional[float] = ..., col27: _Optional[float] = ..., col28: _Optional[float] = ..., col29: _Optional[float] = ..., col30: _Optional[float] = ..., col31: _Optional[float] = ..., col32: _Optional[float] = ..., col33: _Optional[float] = ..., col34: _Optional[float] = ..., col35: _Optional[float] = ..., col36: _Optional[float] = ..., col37: _Optional[float] = ..., col38: _Optional[float] = ..., col39: _Optional[float] = ..., col40: _Optional[float] = ..., col41: _Optional[float] = ..., col42: _Optional[float] = ..., col43: _Optional[float] = ..., col44: _Optional[float] = ..., col45: _Optional[float] = ..., col46: _Optional[float] = ..., col47: _Optional[float] = ..., col48: _Optional[float] = ..., col49: _Optional[float] = ..., col50: _Optional[float] = ..., col51: _Optional[float] = ..., col52: _Optional[float] = ..., col53: _Optional[float] = ..., col54: _Optional[float] = ..., col55: _Optional[float] = ..., col56: _Optional[float] = ..., col57: _Optional[float] = ..., col58: _Optional[float] = ..., col59: _Optional[float] = ..., col60: _Optional[float] = ..., col61: _Optional[float] = ..., col62: _Optional[float] = ..., col63: _Optional[float] = ..., col64: _Optional[float] = ..., col65: _Optional[float] = ..., col66: _Optional[float] = ..., col67: _Optional[float] = ..., col68: _Optional[float] = ..., col69: _Optional[float] = ..., col70: _Optional[float] = ..., col71: _Optional[float] = ..., col72: _Optional[float] = ..., col73: _Optional[float] = ..., col74: _Optional[float] = ..., col75: _Optional[float] = ..., col76: _Optional[float] = ..., col77: _Optional[float] = ..., col78: _Optional[float] = ..., col79: _Optional[float] = ..., col80: _Optional[float] = ..., col81: _Optional[float] = ..., col82: _Optional[float] = ..., col83: _Optional[float] = ..., col84: _Optional[float] = ..., col85: _Optional[float] = ..., col86: _Optional[float] = ..., col87: _Optional[float] = ..., col88: _Optional[float] = ..., col89: _Optional[float] = ..., col90: _Optional[float] = ..., col91: _Optional[float] = ..., col92: _Optional[float] = ..., col93: _Optional[float] = ..., col94: _Optional[float] = ..., col95: _Optional[float] = ..., col96: _Optional[float] = ..., col97: _Optional[float] = ..., col98: _Optional[float] = ..., col99: _Optional[float] = ..., col100: _Optional[float] = ...) -> None: ...

class OrderRequest(_message.Message):
    __slots__ = []
    def __init__(self) -> None: ...

class OrderResponse(_message.Message):
    __slots__ = ["orders"]
    ORDERS_FIELD_NUMBER: _ClassVar[int]
    orders: _containers.RepeatedCompositeFieldContainer[Order]
    def __init__(self, orders: _Optional[_Iterable[_Union[Order, _Mapping]]] = ...) -> None: ...
