# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import table_pb2 as table__pb2


class TablesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRowTable = channel.unary_unary(
                '/Tables/GetRowTable',
                request_serializer=table__pb2.TableRequest.SerializeToString,
                response_deserializer=table__pb2.RowBasedTable.FromString,
                )
        self.GetColumnTable = channel.unary_unary(
                '/Tables/GetColumnTable',
                request_serializer=table__pb2.TableRequest.SerializeToString,
                response_deserializer=table__pb2.ColumnBasedTable.FromString,
                )


class TablesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRowTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetColumnTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TablesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRowTable': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRowTable,
                    request_deserializer=table__pb2.TableRequest.FromString,
                    response_serializer=table__pb2.RowBasedTable.SerializeToString,
            ),
            'GetColumnTable': grpc.unary_unary_rpc_method_handler(
                    servicer.GetColumnTable,
                    request_deserializer=table__pb2.TableRequest.FromString,
                    response_serializer=table__pb2.ColumnBasedTable.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Tables', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Tables(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRowTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Tables/GetRowTable',
            table__pb2.TableRequest.SerializeToString,
            table__pb2.RowBasedTable.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetColumnTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Tables/GetColumnTable',
            table__pb2.TableRequest.SerializeToString,
            table__pb2.ColumnBasedTable.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
