# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btable.proto\"\x1c\n\x03Row\x12\x15\n\x06values\x18\x01 \x03(\x0b\x32\x05.Cell\"J\n\x04\x43\x65ll\x12\x12\n\x08\x66loatVal\x18\x01 \x01(\x02H\x00\x12\x10\n\x06intVal\x18\x02 \x01(\x03H\x00\x12\x13\n\tstringVal\x18\x03 \x01(\tH\x00\x42\x07\n\x05value\"8\n\rRowBasedTable\x12\x13\n\x0b\x63olumnNames\x18\x01 \x03(\t\x12\x12\n\x04rows\x18\x02 \x03(\x0b\x32\x04.Row\"\x8d\x01\n\x06\x43olumn\x12\x0c\n\x04name\x18\x01 \x01(\t\x12#\n\x0b\x66loatColumn\x18\x02 \x01(\x0b\x32\x0c.FloatColumnH\x00\x12\x1f\n\tintColumn\x18\x03 \x01(\x0b\x32\n.IntColumnH\x00\x12%\n\x0cstringColumn\x18\x04 \x01(\x0b\x32\r.StringColumnH\x00\x42\x08\n\x06values\"\x1b\n\tIntColumn\x12\x0e\n\x06values\x18\x01 \x03(\x03\"\x1e\n\x0cStringColumn\x12\x0e\n\x06values\x18\x01 \x03(\t\"\x1d\n\x0b\x46loatColumn\x12\x0e\n\x06values\x18\x01 \x03(\x02\")\n\x10\x43olumnBasedTable\x12\x15\n\x04\x63ols\x18\x01 \x03(\x0b\x32\x07.Column\"\x1c\n\x0cTableRequest\x12\x0c\n\x04name\x18\x01 \x01(\t2n\n\x06Tables\x12.\n\x0bGetRowTable\x12\r.TableRequest\x1a\x0e.RowBasedTable\"\x00\x12\x34\n\x0eGetColumnTable\x12\r.TableRequest\x1a\x11.ColumnBasedTable\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'table_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROW._serialized_start=15
  _ROW._serialized_end=43
  _CELL._serialized_start=45
  _CELL._serialized_end=119
  _ROWBASEDTABLE._serialized_start=121
  _ROWBASEDTABLE._serialized_end=177
  _COLUMN._serialized_start=180
  _COLUMN._serialized_end=321
  _INTCOLUMN._serialized_start=323
  _INTCOLUMN._serialized_end=350
  _STRINGCOLUMN._serialized_start=352
  _STRINGCOLUMN._serialized_end=382
  _FLOATCOLUMN._serialized_start=384
  _FLOATCOLUMN._serialized_end=413
  _COLUMNBASEDTABLE._serialized_start=415
  _COLUMNBASEDTABLE._serialized_end=456
  _TABLEREQUEST._serialized_start=458
  _TABLEREQUEST._serialized_end=486
  _TABLES._serialized_start=488
  _TABLES._serialized_end=598
# @@protoc_insertion_point(module_scope)
